
from setuptools import setup, find_packages
from Cython.Build import cythonize

setup(
    name="chan_czsc",
    version="0.1",
    packages=find_packages(),
    ext_modules=cythonize([
        "./ChanConfig.pyx",
        "./Chan.pyx",
        "./DataAPI/ccxt.pyx",
        "./DataAPI/CommonStockAPI.pyx",
        "./DataAPI/BaoStockAPI.pyx",
        "./DataAPI/dataframeAPI.pyx",
        "./DataAPI/csvAPI.pyx",
        "./Combiner/Combine_Item.pyx",
        "./Combiner/KLine_Combiner.pyx",
        "./Math/KDJ.pyx",
        "./Math/TrendModel.pyx",
        "./Math/MACD.pyx",
        "./Math/TrendLine.pyx",
        "./Math/RSI.pyx",
        "./Math/BOLL.pyx",
        "./Common/ChanException.pyx",
        "./Common/func_util.pyx",
        "./Common/cache.pyx",
        "./Common/CTime.pyx",
        "./Common/CEnum.pyx",
        "./ZS/ZSList.pyx",
        "./ZS/ZSConfig.pyx",
        "./ZS/ZS.pyx",
        "./ChanModel/Features.pyx",
        "./Bi/Bi.pyx",
        "./Bi/BiList.pyx",
        "./Bi/BiConfig.pyx",
        "./KLine/KLine_List.pyx",
        "./KLine/KLine_Unit.pyx",
        "./KLine/KLine.pyx",
        "./KLine/TradeInfo.pyx",
        "./Seg/EigenFX.pyx",
        "./Seg/SegListChan.pyx",
        "./Seg/SegListComm.pyx",
        "./Seg/Eigen.pyx",
        "./Seg/Seg.pyx",
        "./Seg/SegConfig.pyx"
    ], compiler_directives={'language_level': "3"}),
    zip_safe=False,
)
